# Terraform APPLY Pipeline configuration

parameters:
- name: environment
  displayName: Environment OneManITArmy
  type: string
  values:
  - dev
  - test
  - acc
  - prod

# Create if statement to decide which environment Terraform needs to deploy.
variables:
  ${{ if eq(parameters.environment, 'dev') }}:
    serviceConnectionName: "onemanitarmy dev service connection"         # Specify service connection name in Azure DevOps project settings.
    workingDirectory: '$(System.DefaultWorkingDirectory)'            # Specify working directory of your Terraform files.
    varFile: "$(System.DefaultWorkingDirectory)/env-tfvars/${{ parameters.environment }}.tfvars"
    backendResourceGroupName: "<your tfstate resource group name>"              # Specify RG-name that is created via Terraform where Storage account is held.
    backendStorageAccountName: "<your existing storage account name>"                        # Specify name of the Storage account is that created.
    backendContainerName: "<your tfstate blob container name>"                                  # Specify name of blob container in Storage account.
    backendKey: "<your tfstate backendkey name>.terraform.tfstate"                 # Specify filename mentioned in blob container above.
  ${{ if eq(parameters.environment, 'test') }}:
    serviceConnectionName: "onemanitarmy test service connection"         
    workingDirectory: '$(System.DefaultWorkingDirectory)'            
    varFile: "$(System.DefaultWorkingDirectory)/env-tfvars/${{ parameters.environment }}.tfvars"
    backendResourceGroupName: "<your tfstate resource group name>"              
    backendStorageAccountName: "<your existing storage account name>"                        
    backendContainerName: "<your tfstate blob container name>"                                  
    backendKey: "<your tfstate backendkey name>.terraform.tfstate" 
  ${{ if eq(parameters.environment, 'acc') }}:
    serviceConnectionName: "onemanitarmy acc service connection"         
    workingDirectory: '$(System.DefaultWorkingDirectory)'            
    varFile: "$(System.DefaultWorkingDirectory)/env-tfvars/${{ parameters.environment }}.tfvars"
    backendResourceGroupName: "<your tfstate resource group name>"              
    backendStorageAccountName: "<your existing storage account name>"                        
    backendContainerName: "<your tfstate blob container name>"                                  
    backendKey: "<your tfstate backendkey name>.terraform.tfstate"
  ${{ if eq(parameters.environment, 'prod') }}:
    serviceConnectionName: "onemanitarmy prod service connection"         
    workingDirectory: '$(System.DefaultWorkingDirectory)'            
    varFile: "$(System.DefaultWorkingDirectory)/env-tfvars/${{ parameters.environment }}.tfvars"
    backendResourceGroupName: "<your tfstate resource group name>"              
    backendStorageAccountName: "<your existing storage account name>"                        
    backendContainerName: "<your tfstate blob container name>"                                  
    backendKey: "<your tfstate backendkey name>.terraform.tfstate"                             


trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

stages:

  # Performs Terraform Init, Validate, and Plan.
  - stage: applicationinsights
    jobs:
    - job: validate
      continueOnError: false
      steps:

        # Powershell task to enable Storage Account public access so .tfstate file can be opened and modified.
        - task: AzurePowerShell@5
          displayName: 'Temporarily Allow Public Network Access to Terraform Backend Storage Account'
          inputs:
            azureSubscription: '$(serviceConnectionName)'
            ScriptType: 'InlineScript'
            Inline: |
              # Enable Public Network Access Terraform Backend Storage Account
              Set-AzStorageAccount -ResourceGroupName "$(backendResourceGroupName)" -Name "$(backendStorageAccountName)" -PublicNetworkAccess Enabled
              Start-Sleep -Seconds 60
            azurePowerShellVersion: 'LatestVersion'

        # Perform Terraform Init          
        - task: TerraformTaskV2@2
          displayName: "init"
          inputs:
            provider: "azurerm"
            command: "init"
            workingDirectory: "$(workingDirectory)"
            backendServiceArm: "$(serviceConnectionName)"
            backendAzureRmResourceGroupName: "$(backendResourceGroupName)"
            backendAzureRmStorageAccountName: "$(backendStorageAccountName)"
            backendAzureRmContainerName: "$(backendContainerName)"
            backendAzureRmKey: "$(backendKey)"

        # Perform Terraform Validate        
        - task: TerraformTaskV2@2
          inputs:
            provider: "azurerm"
            command: "validate"

    # Perform Terraform Init once more after validating the code.   
    - deployment: apply_terraform
      dependsOn: validate
      continueOnError: false
      environment: "gen-terraform-env"
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: TerraformTaskV2@2
                displayName: "init"
                inputs:
                  provider: "azurerm"
                  command: "init"
                  workingDirectory: "$(workingDirectory)"
                  backendServiceArm: "$(serviceConnectionName)"
                  backendAzureRmResourceGroupName: "$(backendResourceGroupName)"
                  backendAzureRmStorageAccountName: "$(backendStorageAccountName)"
                  backendAzureRmContainerName: "$(backendContainerName)"
                  backendAzureRmKey: "$(backendKey)"

              # Perform Terraform Apply     
              - task: TerraformTaskV2@2
                displayName: "apply"
                inputs:
                  provider: "azurerm"
                  command: "apply"
                  workingDirectory: "$(workingDirectory)"
                  commandOptions: '-var-file="$(varFile)" -var="backendResourceGroupName=$(backendResourceGroupName)" -var="backendStorageAccountName=$(backendStorageAccountName)" -var="backendContainerName=$(backendContainerName)" -var="backendKey=$(backendKey)"'
                  environmentServiceNameAzureRM: "$(serviceConnectionName)"
              
              # Powershell job to disable Storage Account public access so .tfstate file is secured. 
              - task: AzurePowerShell@5
                displayName: 'Disable Public Network Access to Terraform Backend Storage Account'
                inputs:
                  azureSubscription: '$(serviceConnectionName)'
                  ScriptType: 'InlineScript'
                  Inline: |
                    # Disable Public Network Access
                    Set-AzStorageAccount -ResourceGroupName "$(backendResourceGroupName)" -Name "$(backendStorageAccountName)" -PublicNetworkAccess Disabled
                  azurePowerShellVersion: 'LatestVersion'

    # Error handling                              
    - job: catch_failed_apply
      dependsOn: apply_terraform
      condition: failed()
      continueOnError: false
      steps:
        - task: AzurePowerShell@5
          displayName: 'Disable Public Network Access to Terraform Backend Storage Account'
          inputs:
            azureSubscription: '$(serviceConnectionName)'
            ScriptType: 'InlineScript'
            Inline: |
              # Disable Public Network Access Terraform Backend Storage Account.
              Set-AzStorageAccount -ResourceGroupName "$(backendResourceGroupName)" -Name "$(backendStorageAccountName)" -PublicNetworkAccess Disabled
            azurePowerShellVersion: 'LatestVersion'
